name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman
        uses: buluma/pacman-contribution-graph@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jeswinbenedict
          OUTPUT_DIRECTORY: dist

      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
